use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ProviderRegion {
    Local,
    Global,
    Cn,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ProviderKind {
    Ollama,
    OpenAI,
    Anthropic,
    Gemini,
    MiniMax,
    Glm,
    DeepSeek,
    Qwen,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProviderProfile {
    pub id: String,
    pub label: String,
    pub kind: ProviderKind,
    pub region: ProviderRegion,
    pub base_url: String,
    pub requires_api_key: bool,
    pub supports_chat: bool,
    pub supports_stream: bool,
    pub supports_embeddings: bool,
    pub supports_tools: bool,
}

pub fn default_provider_profiles() -> Vec<ProviderProfile> {
    vec![
        ProviderProfile {
            id: "ollama-local".to_string(),
            label: "Ollama (Local)".to_string(),
            kind: ProviderKind::Ollama,
            region: ProviderRegion::Local,
            base_url: "http://localhost:11434".to_string(),
            requires_api_key: false,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: true,
            supports_tools: false,
        },
        ProviderProfile {
            id: "openai-global".to_string(),
            label: "OpenAI".to_string(),
            kind: ProviderKind::OpenAI,
            region: ProviderRegion::Global,
            base_url: "https://api.openai.com/v1".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: true,
            supports_tools: true,
        },
        ProviderProfile {
            id: "anthropic-global".to_string(),
            label: "Anthropic Claude".to_string(),
            kind: ProviderKind::Anthropic,
            region: ProviderRegion::Global,
            base_url: "https://api.anthropic.com".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: false,
            supports_tools: true,
        },
        ProviderProfile {
            id: "gemini-global".to_string(),
            label: "Google Gemini".to_string(),
            kind: ProviderKind::Gemini,
            region: ProviderRegion::Global,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: true,
            supports_tools: true,
        },
        ProviderProfile {
            id: "deepseek-global".to_string(),
            label: "DeepSeek".to_string(),
            kind: ProviderKind::DeepSeek,
            region: ProviderRegion::Global,
            base_url: "https://api.deepseek.com".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: false,
            supports_tools: false,
        },
        ProviderProfile {
            id: "qwen-global".to_string(),
            label: "Qwen".to_string(),
            kind: ProviderKind::Qwen,
            region: ProviderRegion::Global,
            base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: true,
            supports_tools: false,
        },
        ProviderProfile {
            id: "glm-cn".to_string(),
            label: "GLM (China)".to_string(),
            kind: ProviderKind::Glm,
            region: ProviderRegion::Cn,
            base_url: "https://open.bigmodel.cn/api/paas/v4".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: true,
            supports_tools: true,
        },
        ProviderProfile {
            id: "glm-global".to_string(),
            label: "GLM (Global)".to_string(),
            kind: ProviderKind::Glm,
            region: ProviderRegion::Global,
            base_url: "https://open.bigmodel.cn/api/paas/v4".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: true,
            supports_tools: true,
        },
        ProviderProfile {
            id: "minimax-cn".to_string(),
            label: "MiniMax (China)".to_string(),
            kind: ProviderKind::MiniMax,
            region: ProviderRegion::Cn,
            base_url: "https://api.minimax.chat".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: false,
            supports_tools: true,
        },
        ProviderProfile {
            id: "minimax-global".to_string(),
            label: "MiniMax (Global)".to_string(),
            kind: ProviderKind::MiniMax,
            region: ProviderRegion::Global,
            base_url: "https://api.minimaxi.chat".to_string(),
            requires_api_key: true,
            supports_chat: true,
            supports_stream: true,
            supports_embeddings: false,
            supports_tools: true,
        },
    ]
}
